from collections import namedtuple

KeyEventsTuple = namedtuple("KeyEvents", [
    "UNKNOWN",
    "MENU",
    "SOFT_RIGHT",
    "HOME",
    "BACK",
    "CALL",
    "ENDCALL",
    "NUMBER_0",
    "NUMBER_1",
    "NUMBER_2",
    "NUMBER_3",
    "NUMBER_4",
    "NUMBER_5",
    "NUMBER_6",
    "NUMBER_7",
    "NUMBER_8",
    "NUMBER_9",
    "STAR",
    "POUND",
    "DPAD_UP",
    "DPAD_DOWN",
    "DPAD_LEFT",
    "DPAD_RIGHT",
    "DPAD_CENTER",
    "VOLUME_UP",
    "VOLUME_DOWN",
    "POWER",
    "CAMERA",
    "CLEAR",
    "LETTER_A",
    "LETTER_B",
    "LETTER_C",
    "LETTER_D",
    "LETTER_E",
    "LETTER_F",
    "LETTER_G",
    "LETTER_H",
    "LETTER_I",
    "LETTER_J",
    "LETTER_K",
    "LETTER_L",
    "LETTER_M",
    "LETTER_N",
    "LETTER_O",
    "LETTER_P",
    "LETTER_Q",
    "LETTER_R",
    "LETTER_S",
    "LETTER_T",
    "LETTER_U",
    "LETTER_V",
    "LETTER_W",
    "LETTER_X",
    "LETTER_Y",
    "LETTER_Z",
    "COMMA",
    "PERIOD",
    "ALT_LEFT",
    "ALT_RIGHT",
    "SHIFT_LEFT",
    "SHIFT_RIGHT",
    "TAB",
    "SPACE",
    "SYM",
    "EXPLORER",
    "ENVELOPE",
    "ENTER",
    "DEL",
    "GRAVE",
    "MINUS",
    "EQUALS",
    "LEFT_BRACKET",
    "RIGHT_BRACKET",
    "BACKSLASH",
    "SEMICOLON",
    "APOSTROPHE",
    "SLASH",
    "AT",
    "NUM",
    "HEADSETHOOK",
    "FOCUS",
    "PLUS",
    "MENU_2",
    "NOTIFICATION",
    "SEARCH",
    "TAG_LAST_KEYCODE"
])

KeyEvents = KeyEventsTuple(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
                           26, 27, 28, 29, 30, 31,
                           32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54,
                           55, 56, 57, 58, 59, 60,
                           61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
                           84, 85)
