from collections import namedtuple
# https://gist.github.com/tsohr/5711945
IntentFlagsTuple = namedtuple("IntentFlags", [
    "ACTION",
    "DATA_URI",
    "MIME_TYPE",
    "CATEGORY",
    "EXTRA_STRING_VALUE",
    "EXTRA_NULL",
    "EXTRA_BOOLEAN_VALUE",
    "EXTRA_INT_VALUE",
    "EXTRA_LONG_VALUE",
    "EXTRA_FLOAT_VALUE",
    "EXTRA_URI_VALUE",
    "EXTRA_COMPONENT_NAME_VALUE",
    "EXTRA_INT_VALUE_ARRAY",
    "EXTRA_LONG_VALUE_ARRAY",
    "EXTRA_FLOAT_VALUE_ARRAY",
    "COMPONENT",
    "FLAGS",
    "GRANT_READ_URI_PERMISSION",
    "GRANT_WRITE_URI_PERMISSION",
    "DEBUG_LOG_RESOLUTION",
    "EXCLUDE_STOPPED_PACKAGES",
    "INCLUDE_STOPPED_PACKAGES",
    "ACTIVITY_BROUGHT_TO_FRONT",
    "ACTIVITY_CLEAR_TOP",
    "ACTIVITY_CLEAR_WHEN_TASK_RESET",
    "ACTIVITY_EXCLUSE_FROM_RECENTS",
    "ACTIVITY_LAUNCHED_FROM_HISTORY",
    "ACTIVITY_MULTIPLE_TASK",
    "ACTIVITY_NO_ANIMATION",
    "ACTIVITY_NO_HISTORY",
    "ACTIVITY_NO_USER_ACTION",
    "ACTIVITY_PREVIOUS_IS_TOP",
    "ACTIVITY_REORDER_TO_FRONT",
    "ACTIVITY_RESET_TASK_IF_NEEDED",
    "ACTIVITY_SINGLE_TOP",
    "ACTIVITY_CLEAR_TASK",
    "ACTIVITY_TASK_ON_HOME",
    "RECEIVER_REGISTERED_ONLY",
    "RECEIVER_REPLACE_PENDING",
    "SELECTOR"
])

IntentFlags = IntentFlagsTuple(
    "a", "d", "t", "c", "e", "-esn", "-ez", "-ei", "-el", "-ef", "-eu", "-ecn", "-eia", "-ela", "-efa", "n", "f",
    "-grant-read-uri-permission", "-grant-write-uri-permission", "-debug-log-resolution", "-exclude-stopped-packages",
    "-include-stopped-packages", "-activity-brought-to-front", "-activity-clear-top", "-activity-clear-when-task-reset",
    "-activity-exclude-from-recents", "-activity-launched-from-history", "-activity-multiple-task",
    "-activity-no-animation",
    "-activity-no-history", "-activity-no-user-action", "-activity-previous-is-top", "-activity-reorder-to-front",
    "-activity-reset-task-if-needed",
    "-activity-single-top", "-activity-clear-task", "-activity-task-on-home", "-receiver-registered-only",
    "-receiver-replace-pending",
    "-selector"
)
